### ISSUE TITLE
datasets library not in requirements

### ISSUE THREAD

**Issue by fabiogomez11c** [rasbt/pytorch-memory-optim#1]
@rasbt `datasets` library is not included in `requirements.txt` so  `pip install -r requirements.txt` won't be enough (at least that was in my case), do you want me to add it?

**Comment by rasbt** [comment]
Thanks for the note! I think in my case it was automatically installed with `transformers` but maybe it's not a bad idea to add it explicitly. Just made that quick change and added it with the particular version number I was using.
